; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
board = esp32dev
board_build.f_cpu = 240000000L
lib_deps = 
	e-radionicacom/InkplateLibrary@^10.0.0
	bblanchon/ArduinoJson@^7.4.1
	tzapu/WiFiManager@^2.0.17


[env:debug_inkplate10v2]
monitor_filters = esp32_exception_decoder
build_type = debug
build_unflags = 
	-DARDUINO_ESP32
	-DARDUINO_ESP32_DEV
build_flags = 
	-DARDUINO_INKPLATE10V2
	-DBOARD_HAS_PSRAM
	-DHAS_ARDUINOJSON
	-DYAML_DISABLE_CJSON
	-mfix-esp32-psram-cache-issue
	-DLOG_LEVEL=5
	-DCORE_DEBUG_LEVEL=4

[env:release_inkplate10v2]
build_type = release
build_unflags = 
	-DARDUINO_ESP32
	-DARDUINO_ESP32_DEV
build_flags =
	-DARDUINO_INKPLATE10V2
	-DBOARD_HAS_PSRAM
	-DHAS_ARDUINOJSON
	-DYAML_DISABLE_CJSON
	-mfix-esp32-psram-cache-issue
	-DLOG_LEVEL=4
	-DCORE_DEBUG_LEVEL=0


[env:debug_inkplate5v2]
monitor_filters = esp32_exception_decoder
build_type = debug
build_unflags = 
	-DARDUINO_ESP32
	-DARDUINO_ESP32_DEV
build_flags = 
	-DARDUINO_INKPLATE5V2
	-DBOARD_HAS_PSRAM
	-DHAS_ARDUINOJSON
	-DYAML_DISABLE_CJSON
	-mfix-esp32-psram-cache-issue
	-DLOG_LEVEL=5
	-DCORE_DEBUG_LEVEL=4

[env:release_inkplate5v2]
build_type = release
build_unflags = 
	-DARDUINO_ESP32
	-DARDUINO_ESP32_DEV
build_flags =
	-DARDUINO_INKPLATE5V2
	-DBOARD_HAS_PSRAM
	-DHAS_ARDUINOJSON
	-DYAML_DISABLE_CJSON
	-mfix-esp32-psram-cache-issue
	-DLOG_LEVEL=4
	-DCORE_DEBUG_LEVEL=0